# Site settings
title: Brant Padak's Profile
email: brantpadak@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/project-gh-pages-24"
url: "http://BrantPadak.github.io"
twitter_username: HumanBullseye
github_username:  BrantPadak
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
